advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view()),
    path('basic_app/', include('basic_app.urls', namespace='basic_app')),
]

advcbv/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('', views.SchoolListView.as_view(), name='list'),
    path('create/', views.SchoolCreateView.as_view(), name='create'),
    path('<int:pk>/', views.SchoolDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.SchoolUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.SchoolDeleteView.as_view(), name='delete'),
]

advcbv/basic_app/models.py
from django.db import models
from django.urls import reverse

class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("basic_app:detail", kwargs={"pk": self.pk})
    
    
class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.IntegerField()
    school = models.ForeignKey(School, on_delete=models.CASCADE, related_name='students')
    
    def __str__(self):
        return self.name
    

advcbv/basic_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from . import models

class IndexView(TemplateView):
    template_name = 'index.html'
    
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['injectme'] = 'BASIC INJECTION!'
    #     return context

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School


class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'
    
    
class SchoolCreateView(CreateView):
    fields = ('name', 'principal', 'location')
    model = models.School
    template_name = 'basic_app/school_form.html'
    
    
class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal')
    model = models.School
    
class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy('basic_app:list')

advcbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>BASE!</title>
        <!-- Latest compiled and minified CSS -->
        <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
            integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
            crossorigin="anonymous"
        />
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <ul class="nav navbar-nav">
                <li>
                    <a class="navbar-brand" href="{% url 'basic_app:list' %}"
                        >Schools</a
                    >
                </li>
                <li>
                    <a class="navbar-link" href="{% url 'admin:index' %}"
                        >Admin</a
                    >
                </li>
                <li>
                    <a class="navbar-link" href="{% url 'basic_app:list' %}"
                        >Schools</a
                    >
                </li>
            </ul>
        </nav>
        <div class="container">{% block body_block %} {% endblock %}</div>
    </body>
</html>

advcbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %} {% block body_block %}
<h1>Delete {{school.name}}?</h1>

<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete" />
    <!-- NOTE: here we must pass the pk=school.pk because in the basic_app:detail view, in urls.py
    the regex expects a primary key value (pk) -->
    <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
</form>
{% endblock %}

advcbv/basic_app/templates/basic_app/school_detail.html
{% extends 'basic_app/basic_app_base.html' %} {% block body_block %}
<div class="jumbotron">
    <h1>Welcome to the School Detailed page!</h1>
    <h2>School details:</h2>
    <p>Name: {{school_detail.name}}</p>
    <p>Principal: {{school_detail.principal}}</p>
    <p>Location: {{school_detail.location}}</p>

    <h3>Students</h3>
    <!-- NOTE: the school_list is the context_object_name we provided in basic_app/views.py
    The tricky part here is the school_detail.students . This is the related_name on students.
    It is like going to the SQL and query for all students in that particular school, since school
  is a ForeignKey for the Student.  -->
    {% for student in school_detail.students.all %}
    <p>{{student.name}} who is {{student.age}} years old.</p>
    {% endfor %}
</div>

<div class="container">
    <p>
        <a
            class="btn btn-warning"
            href="{% url 'basic_app:update' pk=school_detail.pk%}"
            >Update</a
        >
    </p>
    <p>
        <a
            class="btn btn-danger"
            href="{% url 'basic_app:delete' pk=school_detail.pk%}"
            >Delete</a
        >
    </p>
</div>

{% endblock %}

advcbv/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html" %} {% block body_block %}
<h1>
    {# prettier-ignore #} {% if not form.instance.pk %} Create school {% else %}
    Update school {% endif %}
</h1>

<form method="post">
    {% csrf_token %} {{ form.as_p }}
    <input type="submit" name="btn btn-primary" value="Submit" />
</form>
{% endblock %}

advcbv/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %} {% block body_block %}
<h1>Wecome to a list of all the schools!</h1>
<ol>
    {% for school in schools %}
    <h2>
        <li><a href="{{school.id}}">{{school.name}}</a></li>
    </h2>
    {% endfor %}
    <p>
        <a class="btn btn-success" href="{% url 'basic_app:create' %}"
            >Create</a
        >
    </p>
</ol>
{% endblock %}

advcbv/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>BASE!</title>
        <!-- Latest compiled and minified CSS -->
        <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
            integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
            crossorigin="anonymous"
        />
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <ul class="nav navbar-nav">
                <!-- Remmember: the URL template is referring to basic_app urls.py, and calling the URL named 'list' -->
                <li>
                    <a class="navbar-brand" href="{% url 'basic_app:list' %}"
                        >Schools</a
                    >
                </li>
                <li>
                    <a class="navbar-link" href="{% url 'admin:index' %}"
                        >Admin</a
                    >
                </li>
                <li>
                    <a
                        class="navbar-link"
                        href="{% url 'basic_app:list' %}"
                    ></a>
                </li>
            </ul>
        </nav>
        <div class="container">{% block body_block %} {% endblock %}</div>
    </body>
</html>

advcbv/templates/index.html
{% extends "base.html" %} {% block body_block %}
<div class="jumbotron">
    <h1>Home page!</h1>
</div>
{% endblock %}